from kivy.app import App





'''
TODO LIST

1. FIGURE OUT CODE ARCHITECTURE (HARD)
2. DISPLAY THE PIECES AND MAKE IT LOOK SEEMLESS (easy when code arch. is finished)
2.5 CODE A DRAGGING SYSTEM AND A TOUCH-BASED SYSTEM
    2.75 MAKE THE DRAGGING SYSTEM HAVE THE PIECES MOVE A LAYER UP FROM THE BOARD
3. CODE ALL OF THE MOVES FOR THE PIECES (HARD; MAKE CODE STILL NEAT)
4. CREATE A SYSTEM OF TURN-BASED GAMEPLAY (MEDIUM; NEED TO KEEP CODE CLEAN)
5. CREATE A SYSTEM TO SHOW THE USER WHERE TO PLACE: AND A CHECK-BASED SYSTEM
6. CREATE A SYSTEM FOR KILLING OTHER PIECES

DONE;
THE GAMEPLAY SHOULD BE BASICALLY DONE

'''
